services:
  postgres:
    image: postgres:15-alpine
    container_name: dsflow-postgres
    environment:
      POSTGRES_DB: dsflow
      POSTGRES_USER: dsflow
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dsflow-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: dsflow-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dsflow
      DB_USERNAME: dsflow
      DB_PASSWORD: password
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - dsflow-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: dsflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dsflow-network
    restart: unless-stopped

networks:
  dsflow-network:
    driver: bridge

volumes:
  postgres_data: 